In [6]:
import pandas as pd

In [7]:
prices_df=pd.read_csv('/home/slawomir/Portfolio/blog_articles/Choose_the_best_hours/prices.csv', parse_dates=['Date'], index_col='Date')

In [8]:
spreads_df=pd.read_csv('/home/slawomir/Portfolio/blog_articles/Choose_the_best_hours/spreads.csv', parse_dates=['Date'], index_col='Date')

In [9]:
prices_df

,EURAUD,AUDNZD,GBPMXN,GBPJPY,USDSEK,EURJPY,EURMXN,CHFPLN,USDJPY,USDMXN,...,EURCAD,EURGBP,EURUSD,EURPLN,CHFHUF,CADCHF,EURTRY,AUDCAD,USDCAD,NZDCAD
Date,,,,,,,,,,,,,,,,,,,,,
2023-04-05 00:00:00,1.62224,1.07005,22.6566,164.559,10.2628,144.223,19.8582,4.7130,131.709,18.1266,...,1.47286,0.87634,1.09555,4.6772,380.41,0.67360,21.13537,0.90786,1.34440,0.84819
2023-04-05 00:01:00,1.62232,1.07000,22.6588,164.550,10.2628,144.200,19.8582,4.7132,131.677,18.1269,...,1.47292,0.87636,1.09563,4.6772,380.41,0.67357,21.13590,0.90785,1.34448,0.84825
2023-04-05 00:02:00,1.62232,1.06993,22.6588,164.533,10.2628,144.192,19.8581,4.7132,131.681,18.1226,...,1.47291,0.87638,1.09560,4.6772,380.41,0.67363,21.14746,0.90780,1.34439,0.84821
2023-04-05 00:03:00,1.62232,1.06989,22.6589,164.528,10.2648,144.188,19.8582,4.7131,131.677,18.1227,...,1.47292,0.87635,1.09557,4.6772,380.41,0.67360,21.14699,0.90783,1.34445,0.84824
2023-04-05 00:04:00,1.62243,1.06986,22.6566,164.527,10.2659,144.190,19.8582,4.7130,131.680,18.1227,...,1.47291,0.87635,1.09553,4.6772,380.41,0.67360,21.14616,0.90773,1.34445,0.84824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-05 23:55:00,1.62235,1.06375,22.7905,163.536,10.3783,143.150,19.9368,4.7361,131.293,18.2959,...,1.46762,0.87513,1.09051,4.6804,380.31,0.67265,20.95434,0.90457,1.34584,0.85012
2023-04-05 23:56:00,1.62251,1.06368,22.7905,163.512,10.3783,143.133,19.9368,4.7361,131.280,18.2959,...,1.46674,0.87513,1.09053,4.6804,380.31,0.67261,20.95434,0.90393,1.34501,0.84972
2023-04-05 23:57:00,1.62241,1.06384,22.7905,163.507,10.3783,143.151,19.9384,4.7361,131.279,18.2959,...,1.46709,0.87528,1.09065,4.6804,380.31,0.67262,21.00260,0.90426,1.34464,0.84986
2023-04-05 23:58:00,1.62238,1.06387,22.7905,163.507,10.3783,143.133,19.9384,4.7361,131.279,18.2959,...,1.46715,0.87524,1.09058,4.6804,380.31,0.67262,21.00190,0.90426,1.34464,0.84986
2023-04-05 23:59:00,1.62238,1.06387,22.7905,163.453,10.3783,143.091,19.9384,4.7361,131.240,18.2959,...,1.46710,0.87524,1.09059,4.6804,380.31,0.67275,20.99895,0.90425,1.34526,0.84985

In [10]:
spreads_df

,EURAUD,AUDNZD,GBPMXN,GBPJPY,USDSEK,EURJPY,EURMXN,CHFPLN,USDJPY,USDMXN,...,EURGBP,EURUSD,EURPLN,CHFHUF,CADCHF,EURTRY,AUDCAD,USDCAD,NZDCAD,hour
Date,,,,,,,,,,,,,,,,,,,,,
2023-04-05 00:00:00,0.000285,0.000300,0.03590,0.0305,0.02750,0.016,0.01395,0.00655,0.022,0.0248,...,0.000165,0.000090,0.01185,0.925,0.00041,0.057520,0.000255,0.000260,0.000405,0
2023-04-05 00:01:00,0.000285,0.000300,0.03590,0.0305,0.02750,0.016,0.01395,0.00655,0.022,0.0248,...,0.000165,0.000090,0.01185,0.925,0.00041,0.057520,0.000255,0.000260,0.000405,0
2023-04-05 00:02:00,0.000285,0.000300,0.03590,0.0305,0.02750,0.016,0.01395,0.00655,0.022,0.0248,...,0.000165,0.000090,0.01185,0.925,0.00041,0.057520,0.000255,0.000260,0.000405,0
2023-04-05 00:03:00,0.000285,0.000300,0.03590,0.0305,0.02750,0.016,0.01395,0.00655,0.022,0.0248,...,0.000165,0.000090,0.01185,0.925,0.00041,0.057520,0.000255,0.000260,0.000405,0
2023-04-05 00:04:00,0.000285,0.000300,0.03590,0.0305,0.02750,0.016,0.01395,0.00655,0.022,0.0248,...,0.000165,0.000090,0.01185,0.925,0.00041,0.057520,0.000255,0.000260,0.000405,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-05 23:55:00,0.000950,0.001375,0.02435,0.1215,0.03525,0.037,0.01915,0.00755,0.037,0.0167,...,0.000140,0.000385,0.00725,1.380,0.00083,0.022333,0.000770,0.000415,0.001230,23
2023-04-05 23:56:00,0.000950,0.001375,0.02435,0.1215,0.03525,0.037,0.01915,0.00755,0.037,0.0167,...,0.000140,0.000385,0.00725,1.380,0.00083,0.022333,0.000770,0.000415,0.001230,23
2023-04-05 23:57:00,0.000950,0.001375,0.02435,0.1215,0.03525,0.037,0.01915,0.00755,0.037,0.0167,...,0.000140,0.000385,0.00725,1.380,0.00083,0.022333,0.000770,0.000415,0.001230,23
2023-04-05 23:58:00,0.000950,0.001375,0.02435,0.1215,0.03525,0.037,0.01915,0.00755,0.037,0.0167,...,0.000140,0.000385,0.00725,1.380,0.00083,0.022333,0.000770,0.000415,0.001230,23
2023-04-05 23:59:00,0.000950,0.001375,0.02435,0.1215,0.03525,0.037,0.01915,0.00755,0.037,0.0167,...,0.000140,0.000385,0.00725,1.380,0.00083,0.022333,0.000770,0.000415,0.001230,23